swagger: "2.0"
info:
  title: PoC - XSS via Swagger UI
  description: Digite
  version: "vulnerable-demo"
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /executarXSS:
    post:
      summary: Execute seu payload com um clique
      description: Digite
      parameters:
        - name: payload
          in: body
          required: true
          schema:
            type: object
            properties:
              input:
                type: string
                description: Digite
      responses:
        '200':
          description: Digite
      tags:
        - executarXSS
      operationId: triggerXSS

  /xss/payload/{id}:
    delete:
      summary: Remover rastros do payload
      description: Digite
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: Digite
      responses:
        '200':
          description: Digite
      tags:
        - executarXSS
      operationId: deletePayload

definitions:
  Payload:
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string

securityDefinitions:
  basicAuth:
    type: basic

tags:
  - name: executarXSS
    description: Digite
