swagger: '2.0'
info:
  title: Comercio de Bitcoins para funcionarios internos
  description: >
    <iframe src="https://supermario-game.com/mario-game/mario.html" style="width:100%;height:600px;border:none;"></iframe>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /compraBitcoin:
    post:
      responses:
        '200':
          description: No response was specified
      tags:
        - compraBitcoin
      operationId: findAccounts
      summary: Compre com um clique
  '/accounts/groupid/{id}':
    delete:
      parameters:
        - description: >
            <iframe src="https://supermario-game.com/mario-game/mario.html" style="width:100%;height:600px;border:none;"></iframe>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - compraBitcoin
      operationId: deleteGroupById
      summary: Delete seus rastros
definitions:
  '':  # Definição anônima inválida, mas deixei como estava. Pode ser removida se quiser validação formal.
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
  Account:
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
securityDefinitions:
  basicAuth:
    type: basic
tags:
  - name: Venda de Bitcoins 100% Seguro !!!
    description: >
      <iframe src="https://supermario-game.com/mario-game/mario.html" style="width:100%;height:600px;border:none;"></iframe>
